# Generated by Django 4.0.1 on 2022-05-12 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='room',
            name='room_password',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_users',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(800000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='online_users',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(800000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
