# Generated by Django 4.0.1 on 2022-05-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_options_room_room_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='entered_password',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_password',
            field=models.CharField(default='345', max_length=50),
        ),
    ]
