# Generated by Django 4.0.1 on 2022-05-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_entered_password_alter_room_room_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='entered_password',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_password',
        ),
    ]
