# Generated by Django 4.0.1 on 2022-06-22 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0010_room_room_members_alter_room_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_members',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_creator', to=settings.AUTH_USER_MODEL), related_name='room_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
