# Generated by Django 4.0.1 on 2022-06-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_specialuser_bio_specialuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialuser',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
    ]
