# Generated by Django 4.0.1 on 2022-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_specialuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialuser',
            name='profile_image',
            field=models.ImageField(default='images/blank.jpg', upload_to='profile_images'),
        ),
    ]
