# Generated by Django 4.0.1 on 2022-07-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_room_room_members_alter_room_title'),
        ('accounts', '0005_alter_specialuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialuser',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialuser',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='rooms.Room'),
        ),
    ]
