# Generated by Django 4.0.1 on 2022-06-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
